### ISSUE TITLE
after proceedToChooseAccount, workflow does not end, hangs on "Accessing account information"

### ISSUE THREAD

**Issue by danshieldspala** [TrustlyInc/trustly-android-example#4]
Using trustly-android-example with credentials generated by our platform test environment, we are consistenly able to get to the choose account step on an Android device, but upon submitting 'Continue' it hangs. 

## Steps to Reproduce:

1. The following establishDataValues were provided to selectBank:
```
"customer.email" -> "trustly006@yopmail.com"
"customer.address.address1" -> "1101 East Gibbsboro Road "
"customer.customerId" -> "19019"
"metadata.urlScheme" -> "sdkdemo://"
"customer.externalId" -> "19019"
"customer.address.zip" -> "08021"
"customer.taxId" -> "crypt:/5SX3jF6OzTIuCGjRUBe1I365nRmySF1Sd7zawdEjVc="
"env" -> "sandbox"
"customer.address.state" -> "NJ"
"paymentType" -> "Deferred"
"accessId" -> "WS8vT7ftpHImaeLB5FSx"
"merchantId" -> "1051"
"customer.address.country" -> "US"
"customer.phone" -> "+16575675675"
"merchantReference" -> "1681413404294|TKxEutQDME-WJkCTzCHJyeBXUczl5BYbAd2ZlshfjoTYl-h4hax0cD2APZ_Ei-rr"
"customer.dateOfBirth" -> "1985-01-01"
"customer.name" -> "trustly six"
"customer.address.city" -> "Lindenwold"
"requestSignature" -> "KEWSDvcwa/9T/El7C439wlgUqUk="
```

In the following code fragment from `app/src/main/java/net/trustly/paywithmybanksdkdemoandroid/ui/LightBoxActivity.kt` a breakpoint, in Android Studio, was placed in both of the onReturn and onCancel callback functions.  
```java
lightBoxWidget.establish(establishDataValues)
            .onReturn(
                (PayWithMyBankCallback { _: PayWithMyBank, _: Map<String, String> ->
*                    redirectToScreen(Callback.RETURN)
                })
            ).onCancel(
                (PayWithMyBankCallback { _: PayWithMyBank, _: Map<String, String> ->
*                    redirectToScreen(Callback.CANCEL)
                })
            )
```

2. We searched for 'Oauth' and selected "Oauth Demo Bank" in the drop-down.
3. Select 'CONNECT MY BANK' (bottom of screen)
4. Select 'Connect to OAuth Demo Bank'
5. enter into field Username: foo
6. enter into field Password: bar
7. Click Login, and Confirm
8. 'Choose an account' is displayed
9. Click 'Continue'

10.  Neither callback is triggered at the end of the workflow (after choosing an account).   The workflow hangs in the "Accessing account information" screen (below).

![Screenshot_20230413-151016](https://user-images.githubusercontent.com/130673828/231864331-68adcf61-f55f-4b79-b9e0-0c4070100bc6.png)

**Comment by lukevance** [comment]
Thanks for reporting and updating Dan. Please do create any additional issues as you come across them and we will attempt to review them in a timely manner.
